public with sharing class AL_Strings
{
	public static String LOG_STATUS_NEW  = 'New';
	public static String LOG_STATUS_GOOD = 'Good';
	public static String LOG_STATUS_BAD  = 'Bad';
	public static String LOG_STATUS_DEL  = 'Flag for Deletion';

	public static String RULE_CONDITION_EQUALS   = 'equals';
	public static String RULE_CONDITION_NOT_EQ   = 'does not equal';
	public static String RULE_CONDITION_START_W  = 'starts with';
	public static String RULE_CONDITION_CATCHALL = 'catch all';

}